apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flowcluster.fullname" . }}-redis
  labels:
    {{- include "flowcluster.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "flowcluster.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: redis
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flowcluster.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/service: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
